### ISSUE TITLE
Changes to the WTForms package leading to unexpected behavior in the tutorial

### ISSUE THREAD

**Issue by AlexScheller** [miguelgrinberg/microblog#110]
Not sure if this has been pointed out to you yet or if you noticed, but with version 2.2 of wtforms (see [changes](https://wtforms.readthedocs.io/en/stable/changes.html#version-2-2) and issue [#130](https://github.com/wtforms/wtforms/pull/361), the "DataRequired" and "InputRequired" validators will result in the "required" attribute being rendered in form input tags. This results in browser based client-side validation superseding the server side validation. Not a major issue at all, but you might begin to see some comments from people following along with the tutorial or course (specifically at the [web forms](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iii-web-forms)) step wondering why their login input errors look/behave differently than in the tutorial images.

**Comment by miguelgrinberg** [comment]
This was mentioned to me in a few occasions, but was more an oddity than anything else. The people that notice these are those who use Flask-Babel to offer the application in multiple languages, because these client-side popups do not follow language choices in Flask-Babel and always appear in the language of the browser. I believe it is only Chrome that implements these, I don't recall seeing them on other browsers.

> superseding the server side validation

While I agree with you on the general comment, it is important to note that this change does not replace server validation, it just runs client-side validation in real-time as the form is filled to provide immediate feedback, but the server-side DataRequired/InputRequired validators still run on form submission.

**Comment by AlexScheller** [comment]
Ah that is a specific case.

> it is important to note that this change does not replace server validation, it just runs client-side validation in real-time as the form is filled to provide immediate feedback, but the server-side DataRequired/InputRequired validators still run on form submission.

I brought It up because at least on 64-bit Firefox 60.0.1 on Ubuntu 18.04  you cannot submit a form if all fields with the "required" attribute are not filled out. That's what I meant by the client-side validation superseding the server-side. Someone going through the tutorial at that stage with this issue would never get to see the effect of rendering the errors in the template, because the browser wouldn't let them submit the POST request without filling out the form completely.

This Issue was just intended to let you know that that for many people the behavior exhibited in the tutorial at that point will be different than what they actually see in their browsers. This change to wtforms occurred only 2 days ago however, so it's fairly recent.

I agree with you that the required attribute should be opt in rather than opt out, but perhaps the developers/maintainers of wtforms grew tired of people asking why it wasn't the other way around.

**Comment by miguelgrinberg** [comment]
I have made a small change in chapter 3 of the tutorial to disable browser validation, so that the reader can experiment with the wtforms validators without that interference.
