### ISSUE TITLE
ImportError: cannot import name 'app'

### ISSUE THREAD

**Issue by yg2dras1** [miguelgrinberg/microblog#117]
Hi Miguel, I just recently purchased your book, and sad to say can't even get past the Hello World chapter. For some reason, when I type flask run in the terminal, i am getting this error below. Can you please help? thanks!

(venv) yg2dras1@pcl-01:~/microblog$ flask run
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "microblog", an ImportError was raised:

Traceback (most recent call last):
  File "/home/yg2dras1/microblog/venv/lib/python3.5/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/yg2dras1/microblog/microblog.py", line 1, in <module>
    from app import app
ImportError: cannot import name 'app'

**Comment by miguelgrinberg** [comment]
What is the structure of your files? It seems you don't have an `app` package.

**Comment by yg2dras1** [comment]
Hi Miguel, 

I read the instructions twice and tried to follow it to the letter; so this is what i did:
in section 1.3:
i created an app folder inside the microblog folder

then i created a new file named _init_.py inside the app folder, then typed in the code i saw in the book (i also checked if the code inside is the same as your sample code here in github)

then i created a new file called routes.py inside the app folder, then typed in the code in the book

then i created a file called microblog.py, typed in that single line of code (from app import app), then saved this file under the folder microblog

then while under venv in the terminal, i typed in export FLASK_APP=microblog.py
(i'm using ubuntu by the way)

i received no error messages after this.

then, i typed in flask run.

What i'm not sure of is in VS Code the editor i use, I see these sort of exclamation marks in the 3 files (_init_.py, routes.py, and microblog.py) that seem to indicate that there's errors there. maybe in the "from app import app" line? still fairly new in python (learned it in the past 2 months or so), so I don't think I understand fully what's happening here under the hood.

Much appreciated!

**Comment by miguelgrinberg** [comment]
It's two underscores to the sides of init. Try `__init__.py` instead of `_init_.py`. This is actually a Python standard naming convention for packages.

**Comment by yg2dras1** [comment]
@miguelgrinberg wow, that did the trick. thank you for the prompt responses! on to Chapter 2!

**Comment by kapoorkaran** [comment]
C:\Users\KaranKapoor\Desktop\microblog\app>flask run
 * Serving Flask app " microblog.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "app. microblog".

**Comment by shrey1608** [comment]
Thanks a lot. __init__ did the magic

**Comment by Robertokello11** [comment]
Run.py:
from app import app

if __name__ == '__main__':
    app.run()

views.py
from flask import render_template
from app import app
from .request import get_movies
from .requests import get_movies,get_movie,search_movie
from flask import render_template,request,redirect,url_for
# Views
@app.route('/movie/<int:movie_id>')
def movie(movie_id):

    '''
    View root page function that returns the index page and its data
    '''
    movie = get_movie(id)
    title = f'{movie.title}'

    return render_template('movie.html',title = title,movie = movie)

@app.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    # Getting popular movie
    popular_movies = get_movies('popular')
    upcoming_movie = get_movies('upcoming')
    now_showing_movie = get_movies('now_playing')
    # print(popular_movies)
    title = 'Home - Welcome to The best Movie Review Website Online'

    search_movie = request.args.get('movie_query')

    if search_movie:
        return redirect(url_for('search',movie_name=search_movie))
    else:
     return render_template('index.html', title = title, popular = popular_movies, upcoming = upcoming_movie, now_showing = now_showing_movie )

@app.route('/search/<movie_name>')
def search(movie_name):
    '''
    View function to display the search results
    '''
    movie_name_list = movie_name.split(" ")
    movie_name_format = "+".join(movie_name_list)
    searched_movies = search_movie(movie_name_format)
    title = f'search results for {movie_name}'
    return render_template('search.html',movies = searched_movies)

__init__.py

from flask import Flask
from .config import DevConfig
from flask_bootstrap import Bootstrap
from app import views
from app import error

# Initializing application
app = Flask(__name__,instance_relative_config= True)

# Setting up configuration
app.config.from_object(DevConfig)
app.config.from_pyfile('config.py')

# Initializing Flask Extensions
bootstrap = Bootstrap(app)

from app import views

later when I run into the visual studio terminal
Hello am getting this error what could be the issue
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "/home/moringa/Documents/Core-Flask/Watchlist/app/__init__.py", line 4, in <module>
    from app import views
  File "/home/moringa/Documents/Core-Flask/Watchlist/app/views.py", line 2, in <module>
    from app import app
ImportError: cannot import name 'app' from partially initialized module 'app' (most likely due to a circular import) (/home/moringa/Documents/Core-Flask/Watchlist/app/__init__.py

**Comment by miguelgrinberg** [comment]
@Robertokello11 this is an issue board for the Flask Mega-Tutorial, not a generic help forum. If you have problems with your own application, please use Stack Overflow.
