### ISSUE TITLE
Tasks not being saved (Mega-Tutorial XXII)

### ISSUE THREAD

**Issue by nk9** [miguelgrinberg/microblog#169]
I believe this code is missing a `db.session.commit()`, which means the added Tasks aren't being saved. When later code goes to fetch them, it gets None back (see comment 21 from Mubi [here](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xxii-background-jobs#commentform)) and subsequent errors.

```
    def launch_task(self, name, description, *args, **kwargs):
        rq_job = current_app.task_queue.enqueue('app.tasks.' + name, self.id,
                                                *args, **kwargs)
        task = Task(id=rq_job.get_id(), name=name, description=description,
                    user=self)
        db.session.add(task) #<------ Missing commit
        return task
```

**Comment by miguelgrinberg** [comment]
@nk9, that is actually intended, let me explain.

It is actually a bad practice to insert database commits randomly anywhere in the code. The problem is that there is no way to control what is written to the database, since the commit is not specific to a particular operation, it writes all changes made, regardless of whether the change was made in the line right above or in some unrelated function that executed before.

The accepted practice is to only issue database commits in the highest stack level once a "unit of work" is complete. In the case of a web application, the highest stack level is that of the view function, and the unit of work is a request. Using this approach, the different functions invoked by the view function can add their changes to the database session, but the commit happens at the very end. If any errors were to occur, then Flask-SQLAlchemy will rollback the session, and this guarantees that you don't end up with inconsistencies in your database.

The particular commit for launching a task is here: https://github.com/miguelgrinberg/microblog/blob/a7dac64395c5a6f4e46832e484aafd139b2f729e/app/main/routes.py#L202.

Hope this is clear, let me know if there are any questions.

**Comment by nk9** [comment]
Thanks for explaining, I can see why this is the accepted practice. I also see now that this is discussed in the text of the post. Thanks for taking the time to review with me.
