### ISSUE TITLE
could not import "microblog"

### ISSUE THREAD

**Issue by tomjjoy** [miguelgrinberg/microblog#181]
(venv) Thomass-MacBook-Air:microblog thomasjoy$ export FLASK_APP=microblog.py
(venv) Thomass-MacBook-Air:microblog thomasjoy$ flask run
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "microblog".

**Comment by miguelgrinberg** [comment]
Do you have a microblog.py file in the current directory?

**Comment by wondha22** [comment]
Hello, just started using flask (Version 1.1.1) by following the "microblog" project. I am running the application by exporting the FLASK_APP=microblog.py, then 'flask run'.
However, I would like to start using the .flaskenv file. In the .flaskenv file I have the following;

"FLASK_APP=microblog.py"

I have installed python-dotoenv (version 0.10.3),  created the .flaskenv file in the same directory (project directory) as the microblog.py file. 

With the flask virtual environment activated and having navigated to the project directory, I use 'flask run' only to get the error below;

"Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory."_

Any ideas why?

**Comment by miguelgrinberg** [comment]
Are the quotes that you show around the FLASK_APP setting in your .flaskenv file? Take them out, the file should be just this:

    FLASK_APP=microblog.py

**Comment by wondha22** [comment]
Oh yes the quotes are absent. It is just

FLASK_APP=microblog.py

**Comment by onlinejudge95** [comment]
`flask run` needs a `FLASK_APP` env var already set in the shell context in which we are running this command, if we are setting the `FLASK_APP` var in a `.env` file which is loaded after the process(running `flask run`) starts, isn't it natural for it not to be able to load `FLASK_APP` hence the error? I generally make a shell file or a make command where I only set `FLASK_APP=module:app` before starting `flask run` and loading all other configs like `FLASK_ENV`, `FLASK_DEBUG` etc from the `.env` file

**Comment by miguelgrinberg** [comment]
The `.flaskenv` file is loaded very early, before the application is loaded.

**Comment by mrbiggleswirth** [comment]
@tomjjoy ; Original Poster
> (venv) Thomass-MacBook-Air:microblog thomasjoy$ export FLASK_APP=microblog.py
> (venv) Thomass-MacBook-Air:microblog thomasjoy$ flask run
> 
> Error: Could not import "microblog".

Did Miguel's suggestion from Sep 4 work?

-----------------------------------------------------------

@wondha22 ; Follow-up Poster 1
### Ch. 15.5 Flask Environment Variables
`.env`

What does these files look like on your test machine?

/microblog/**config.py**
/microblog/**microblog.py**

**Comment by wondha22** [comment]
Sorry, not yet on Chapter 15.

**Comment by mrbiggleswirth** [comment]
@tomjjoy ; Original Poster
Since you seem to work on a Mac machine run the Flask server using either of below Python commands.

**Python 2 Environment**
`$ python -m flask run`

**Python 3 Environment**
`$ python3 -m flask run`

This case seems to resemble ticket #188

**Comment by miguelgrinberg** [comment]
@mrbiggleswirth while I appreciate that you are trying to help people solve their issues, you are providing instructions that are different than those I use in the tutorial, and that can add to the confusion. Have you found errors in the tutorial? If you think the tutorial is wrong, then let's discuss that. Otherwise, instead of suggesting alternative ways to do things without explaining why those are better than mine, I think it's best to help people fix their environment to work as shown in the tutorial.

**Comment by mrbiggleswirth** [comment]
@miguelgrinberg Hi,

### Multiple tickets for the same error
I looked at different tickets with this title: `Error: Could not import "microblog"`
And everytime those tickets popped up on the radar the cause always seemed to be different. For a Chapter 1 error I wanted to find a way to streamline the troubleshooting process more efficiently. To narrow down the corridor of possible mistakes people may do when reporting this error.

.

### Microblog book tutorial
The Microblog book tutorial is still solid no mistakes there. It works for both default Python systems as for virtual environment created ones.

.

### OS and distros
But I have found that when people new to Python post this Chapter 1 error their tickets always lack information on what OS and distro version they are using. **_Which are crucial information for troubleshooting this error._** Because different OS and different versions of the same distro might create different behavior when running the official Flask server command: `$ flask run`

When I started learning Flask the official Flask server command didn't behave the same when I ran it on:
* WSL (Windows Subsystem for Linux, "**Ubuntu 16.04 LTS**")
* WSL (Windows Subsystem for Linux, "**Ubuntu 18.04 LTS**")
* Linux guest VM "**Ubuntu 18.04 LTS**"

.

### Mac
After helping a new reader with this same common Chapter 1 error.
https://github.com/miguelgrinberg/microblog/issues/188

It turned out that his Mac distro version also didn't behave as intended when running the official Flask server command: `$ flask run`

.

### Experiencing Python2 and Python3 conflicts
Each of these two implicit Flask server commands can reference both Python2 or Python3 depending on OS and distro versions.
```
$ flask run
$ python -m flask run
```
This explicit Flask server command only references Python3.
```
$ python3 -m flask run
```
**_I suspect that 1/3 of the common Chapter 1 error tickets can be traced to this underlying issue._**
Which the official Flask documentation doesn't seem to clarify in an easily accessible manner for newcomers of Python and Flask.
https://flask.palletsprojects.com/en/1.1.x/quickstart/#what-to-do-if-the-server-does-not-start

I mean the command is partially there in the doc but it doesn't really clarify for a Python and Flask newbie about the Python 2 and Python 3 conflicts that might occur. I think their doc creates more unnecessary questions than answers.
```
$ export FLASK_APP=hello.py
$ python -m flask run
```

.

### Explaining things
Well I would prefer to explain to new readers of the Microblog tutorial about my Flask server command recommendation. But I don't really know how to do that without my explanation turning into a **tl;dr** reply. So I was hoping if I only asked people to try these commands quickly then that would eliminate a lot of troubleshooting back-and-forth time before proceeding deeper with troubleshooting.

Python 2 Environment
`$ python -m flask run`

Python 3 Environment
`$ python3 -m flask run`

**Comment by miguelgrinberg** [comment]
@mrbiggleswirth I stand by what I said. If we agree that the instructions in the tutorial are valid, then its best to help newcomers by discovering what they missed and correcting it, and not by suggesting alternative instructions.

> ... the official Flask server command didn't behave the same when ...

That is not my experience. If you have proof of this, then submit a bug or bugs to the Flask project.

**Comment by mrbiggleswirth** [comment]
@miguelgrinberg Good idea, I shall pay the Flask project a visit.

**Comment by Deepakpratap** [comment]
Well..I face the same issue today. It's more due to I did not follow the project structure properly. This error you can get as well if you are following the project structure.
![snapshot](https://user-images.githubusercontent.com/16176176/126644049-0966997a-e328-41a2-80b3-d91a8ed0aedd.png)

**Comment by mesas998** [comment]
Same experience:
$ flask run
Error: While importing 'microblog', an ImportError was raised.

$ python3 -m flask run
(no problem)
I'd like to know why.

**Comment by miguelgrinberg** [comment]
@mesas998 Are you using and activating a virtual environment? If you aren't, then you are at the mercy of your `PATH` definitions. My guess is that `flask` and `python3` are coming from different installations of Python that you have on your system and for that reason one works and the other doesn't. Use a virtual environment to lock your dependencies, and the problem will be gone.
