### ISSUE TITLE
How to Detect User Online Status

### ISSUE THREAD

**Issue by 41alderson** [miguelgrinberg/microblog#222]
Hi @miguelgrinberg  Thanks For Your Great Tutorials And Books.

is there a way to Detect User Online Status or to get a list of users online?

found nothing when i searched and i have no idea.
please guide me through it.

**Comment by miguelgrinberg** [comment]
@41alderson this is tricky because users aren't constantly connected to the server. Consider that a client will send an HTTP request to get a page from the application and then there is no connection until the user clicks on something on that page and triggers another request to be sent.

A simple approximate that you can implement is to say that any users that were last seen in the last 5 minutes are considered online. You can use the [last_seen](https://github.com/miguelgrinberg/microblog/blob/master/app/models.py#L98) attribute from the user model for this. You can add a method in the model that tells you if the user is online or not:

```python
class User(...):
    # ...

    def is_online(self):
        """A user is online if they were last seen less than 5 minutes ago."""
        return (datetime.utcnow() - self.last_seen).total_seconds() < 5 * 60
```

You can then use this method to generate an online image next to the user's name in templates, for example.

Would this approach work?

If you really need to know if a user is actively connected, then you will need to add a WebSocket connection, which is more complex.

**Comment by 41alderson** [comment]
Had implemented the same,
But the problem was waiting for the user to click onto something. Wanted something that gets user status in real time.

Anyway i will keep it simple by implementing the solution u gave.

Thanks for the help.

**Comment by miguelgrinberg** [comment]
@41alderson How about this. Add a little JavaScript thing in all your pages that "pings" the server by sending a dummy request. That will refresh the `last_seen` value for the logged in user and update the online status.

For example, make it do it once per minute, then change the `is_online` method to looks for a last_seen time closer than 65 seconds or so (to account for small lags). Then your online counter will never be off by more than  about 65 seconds.

Adjust the values as necessary to balance the precision vs. load on your server from the dummy requests.

**Comment by 41alderson** [comment]
@miguelgrinberg thank you.
This is what i wanted.
Thanks a lot.

**Comment by damianduffy** [comment]
The existing Microblog notifications JS could be used to do this. By default it's making a request every 10 seconds.  Just update `before_request()` in routes.py to take advantage of that.
```
@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_active = datetime.utcnow()
        db.session.commit()
```
Every time the notification JS runs, the request should update last_active.  Similar to what @miguelgrinberg has suggested but no need to create a 'dummy' request.

Optionally, I guess you could expand the notification process to `check is_online()` and update the relevant `<div>` on the page with a nice image/icon, similar to how the messages notification pill is updated.
