### ISSUE TITLE
(question) I would like to use babel for export_posts.txt mail text, but can't

### ISSUE THREAD

**Issue by littlegreenbean33** [miguelgrinberg/microblog#235]
Hi,

I was trying to use babel to translate the texts in export_posts(html/txt)

However when I use  ```{{ _("....") }}``` I get an error saying it needs to be in the context of a request. I presume in order to know which language is to be translated the text.

Is there a way I can notify or pass as a parameter the language to ```_(``` or ``` _l(```   ??

BTW ```_l(``` complains as undefined. I wonder where ``` _( ``` is defined for Ninja2 to pick it up

many Thanks.

JC

**Comment by miguelgrinberg** [comment]
Where is the context error exactly? I assume it is in the localeselector function? The problem is that the application's localeselector is coded to get the language from the request object, which does not exist in the background job.

You can code the localeselector function to use the request if a request context is available, but if not to get the language in some other way. For example, you can pass it as an argument to the background job, then set it in the `flask.g` object, which you can get in the locale selector function as long as an application context is set up.

The `_l` symbol does not really exist, it is an alias that I use because the original function is much longer:

from flask_babel import lazy_gettext as _l

**Comment by littlegreenbean33** [comment]
Thanks Miguel for this.

yes it is the localeselector function the one that creates trouble.

My plan was indeed to get the info from the request, store it in ```g```  and make a call like  ```babel.localeselector( lambda : g.locale_now) ``` before the call to render the template....or shall I make the call within the template  ```{{ }}```

That is why I was trying to somehow make a call within the template to python code, to articulate the solution......but I am lost....

Any help appreciated.

JC

**Comment by miguelgrinberg** [comment]
@littlegreenbean33 You are going across processes with this. The only way you can pass the language from the server to the RQ worker is as an argument. None of the Flask variables (request, g, etc.) will make it over to the RQ worker.

Pass it as an argument to the export function, then once you have it, you can put it in the `g` that exists in the worker. The locale selector function cannot be invoked directly, you have to change it so that it gets the language from `g` if it cannot get it from request. For example:

```python
@babel.localeselector
def get_locale():
    if not has_request_context():
        return g.locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
```

**Comment by littlegreenbean33** [comment]
Miguel,

Many thanks for the quick turnaround.

 Indeed I jumped over the issue of separate processes. My bad !!

Will try your suggestion later today. 

JC

**Comment by littlegreenbean33** [comment]
Miguel,

your solution works great. 

Just completed the full course and I have to say is the best value for money I have got for many years. The course is an excellent resource and your explanations to the point.

Many many thanks for your support.

JCG
