### ISSUE TITLE
chapter 17 (app not pointing to mysql db)

### ISSUE THREAD

**Issue by datagene-github** [miguelgrinberg/microblog#260]
Hi Miguel, Please I tried to follow the traditional hosting on linux, but after hosting successfully, I found out that the application was still writing in appdb and the mysql db was empty. I have checked every step and I could not figure it. please I will appreciate your input. Thanks

**Comment by miguelgrinberg** [comment]
Did you set `DATABASE_URL` in the environment? What did you set it to?

**Comment by datagene-github** [comment]
Thanks for the response.this is the details
SECRET_KEY=52cb883e323b48d78a0a36e8e951ba4a
MAIL_SERVER=localhost
MAIL_PORT=25
DATABASE_URL=mysql+pymysql://aacslusr:aacslpwd@localhost:3306/aacsldb

**Comment by miguelgrinberg** [comment]
Okay, so this is what you *think* the environment variable is set to, but we know from your report that it is not. From where did you copy this? This isn't the actual environment, right? This is your .env file, I assume? What you need to do now is figure out why these variables are not applied to the environment when the application runs.

In the tutorial I use the `load_dotenv()` function to import the .env file into the environment. Verify that this happens, and right after the call to load_dotenv print the value of DATABASE_URL to confirm. Also make sure this happens before the configuration is applied, because if you are importing the .env file too late the defaults will be used.

**Comment by datagene-github** [comment]
ok, thanks will give it a go and test

**Comment by datagene-github** [comment]
Hi Miguel
I have gone through the video (installing base dependencies, installing the application and setting up mysql) in chapter 17 and I could not find the step.
, please at what step did you use the load_dotenv() function

**Comment by miguelgrinberg** [comment]
The load_dotenv function has been added earlier, not as part of the deployment. It should be called in config.py before the `Config` class is defined. Look in chapter 15.

**Comment by datagene-github** [comment]
Thank you, will have a quick look

**Comment by datagene-github** [comment]
Thank you miguel, it was the cause of the issue. I skipped the chapter because I did not use the function for search (never realised it was linked), very grateful for the heads up
