### ISSUE TITLE
guess_language-spirit replacement or alternate solution?

### ISSUE THREAD

**Issue by alexkoepke** [miguelgrinberg/microblog#273]
According to guess_language-spirit's [PyPI page](https://pypi.org/project/guess_language-spirit/) it hasn't been updated since March 11, 2017. Also, the home link returns a 404 https://bitbucket.org/spirit/guess_language.

Curious if someone else is maintaining the project somewhere else? maybe there is a better solution? I noticed both the Azure and GPC support detecting languages. Maybe this is a better route for solving this issue?
* https://docs.microsoft.com/en-us/rest/api/cognitiveservices/translatortext/translator/detect
* https://cloud.google.com/translate/docs/basic/detecting-language

**Comment by miguelgrinberg** [comment]
Yes, if you look at the two leading translation services (Microsoft's and Google's) both have endpoints for language detection, so if I had to code this today that's what I would use.

**Comment by alexkoepke** [comment]
@miguelgrinberg thanks for the response! Are you accepting PRs for this project? I have found this tutorial/series to be invaluable and would love to give back. What are your plans for "keeping up with the times"? It seems as if it's gotten one major overhaul already. Sorry if you have already answered this somewhere else.

**Comment by miguelgrinberg** [comment]
You are welcome to submit a PR, but because the structure of this repository is directly related to the tutorial I cannot merge them, but just take them as suggestions that I eventually incorporate into the tutorial and the code.

I'm constantly making changes to the tutorial and the code, by the way, but this is not an area where I feel I need to rush and make a change. The guess-language package does work, and it is very convenient that it is a local package that does not require sending requests to an external service. Replacing it with a service will make posting articles much slower, and avoiding that added delay will require significant changes to how the feature is designed.

**Comment by m-nt-s-no** [comment]
@miguelgrinberg before anything, thank you so much for this tutorial.

I'm having trouble making guess-language work for me. I started this tutorial with Python 2.7, then switched to 3.9 (on Windows). Once I switched, Python started having trouble with the unicode parentheses (u'' and ur'') in the guess_language init file. I'm also getting "NameError: name 'unicode' is not defined."

**Comment by miguelgrinberg** [comment]
@m-nt-s-no you need to include the full stack trace of your error. There is no specific `unicode` in Python 3, all strings are unicode. You may be installing an old and abandoned version of the guess_language package, you did notice that the package is called guess-language-spirit, right?

**Comment by m-nt-s-no** [comment]
@miguelgrinberg thanks for pointing that out, it looks like I have both guess_language and guess_language-spirit.

**Comment by miguelgrinberg** [comment]
@m-nt-s-no okay, then remove the one that is not used.

**Comment by miguelgrinberg** [comment]
Replaced with langdetect package in the tutorial.
