### ISSUE TITLE
Admin Role Assignment Issue

### ISSUE THREAD

**Issue by Dev-Elie** [miguelgrinberg/microblog#310]
I've been following the tutorial on your ebook Flask Web Development, however while creating an Admin user it fails to get the role automatically assigned. 
Here's the full project [link](https://github.com/Dev-Elie/Flask-Blog)
What am I missing ?

**Comment by miguelgrinberg** [comment]
Sorry, but your project is different than mine, I can't really tell you what's wrong if you send me a big project I'm not familiar with and zero context.

Have you debugged this problem? What have you determined? Honestly I think this is more a question for Stack Overflow, since you aren't reporting a bug for this project. I suggest you write a detailed description of the bug and put it on SO. Feel free to give me the link once posted.
