### ISSUE TITLE
Bug in lesson 5 due to werkzeug.urls - url parsing removed

### ISSUE THREAD

**Issue by klinge** [miguelgrinberg/microblog#352]
Url parsing was removed from werkzeug.urls in version 3.0.0. (list of things that was removed [here](https://github.com/pallets/werkzeug/pull/2768))

 This breaks the code in lesson 5 - user login. 

In routes.py it now says: 
`from werkzeug.urls import url_parse`

This needs to be changed to: 
`from urllib.parse import urlparse `

**Comment by miguelgrinberg** [comment]
Thanks. Though this is not a "bug". The issue here is that the Flask team have the habit of making silly/inconsequential backwards incompatible changes. This isn't the first, and it won't be the last, sadly.

This project is fine, in any case, because the requirements.txt file pins the Werkzeug version. I regularly update the project and the tutorial, and this change is scheduled to be included in the next update.

**Comment by klinge** [comment]
I agree that bug might be the wrong word here :) And thanks for your efforts to keep your tutorial up to date even in the face of breaking changes from the Flask team!! 

But as a new user following the tutorial and doing fresh pip install for each depencency I add I get the latest version of all packages and then the example code won't work. I guess many new users will do it that way rather than installing dependencies from the requirements.txt in the github repo.

**Comment by miguelgrinberg** [comment]
Correct. I indicated that this project, as a standalone project, does not need to be changed. The tutorial does need to be updated.

**Comment by miguelgrinberg** [comment]
Closing as this does not apply to the new edition of this tutorial.
