### ISSUE TITLE
login error was reported during deployment?

### ISSUE THREAD

**Issue by JTP-123** [miguelgrinberg/microblog#356]
Hello! I have microblog deployed on public free webiste called pythonanywhere because of windows platform. I finally tried to visit public domain by logging. but error reports:
`"The administrator has been notified. Sorry for the inconvenience!`
So I tried to use <code>flask db init</code> on bash console in pythonanywhere, but error occurs:
`Error: Directory migrations already exists and is not empty`
and `flask db mirgate` reports such error:
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [flask_migrate] Error: Target database is not up to date.
```
I don't know why the logging failed.

**Comment by miguelgrinberg** [comment]
It's hard for me to know exactly how you caused this. But normally on a deployed version of the application you will run `flask db upgrade`, never `init` or `migrate`. It seems to me you have not followed the deployment instructions from the tutorial, this is all covered there.

**Comment by miguelgrinberg** [comment]
I'm not really sure what changes you need to make, because I don't know what operations did you do that put you in the current state.

What I was trying to say that it does not make sense to have a database that has a `user` table, and at the same time you have a migration that needs to be applied that creates a table with that same name. Something that you did created this inconsistency, so what you need to do is undo that. You can edit your database manually, deleting the user table and any other thing that shouldn't be there. This is going to be difficult to do if you don't fully understand what you have done, for that reason I suggest deleting the entire database and starting from scratch might make more sense for you.

**Comment by JTP-123** [comment]
I deleted `app.db` but it still fail to work.

**Comment by miguelgrinberg** [comment]
I did not indicate that deleting the database was the fix. What I suggested was to start over, which means you have to follow the instructions from the tutorial, exactly as given.
