### ISSUE TITLE
ch: 22 -- adding tasks

### ISSUE THREAD

**Issue by eriksays** [miguelgrinberg/microblog#56]
One note on chapter 22 -- after adding the Database model, you might want to add a note to "flask db migrate" and "flask db upgrade" -- by that point I'm sure we should know that, but I still managed to not run the migration.

Also -- something of interest -- I had an error in tasks.py, so when I attempted to run an export, it created the task and sent it along to redis; however, because of the error in tasks.py, redis bombed and moved the task to the 'failed' queue. However, my task doesn't realize that, so it's stuck at "0".

I'm going to add some code to check if the task is in the 'failed' queue and add messaging.

Thanks -- really enjoyed the book thus far.

**Comment by miguelgrinberg** [comment]
Thanks for the feedback.

I thought I had a mention of the migration requirement, but you are right, looks like I forgot. I will add it.

Regarding failures in the task, I put a catch all exception handler to prevent run-time errors from leaving the task stuck. I'm guessing you had a more basic error, maybe a syntax error that prevent the tasks.py module to be imported? For those errors the task will stay stuck in Redis, as you say. But the storage of the task on Redis has an expiration of 500 seconds by default (about 8 min.), so you just need to wait for the task to dissappear from Redis, and then in turn it will go away from the application. If you prefer, you can get in a flask shell and delete the task from the database, so that you don't have to see the green bar for those 8 minutes or so.

**Comment by eriksays** [comment]
Hi -- thanks.

Yes, I had many many syntax errors and ended up going into the flask shell multiple times to clear out the tasks.

So, if I understand, after about 500 seconds, redis would have sent back a "completed" status? Is there a way to catch that redis moved something into the 'failed' queue?

Thanks -- I have enjoyed this rather detailed walkthrough of flask --

**Comment by miguelgrinberg** [comment]
> redis would have sent back a "completed" status

Not really. The data that is stored on Redis for a given task has an expiration time of 500 seconds. After that time it will just disappear.
