### ISSUE TITLE
Ch 19.4.2 - Error when changing Elasticsearch container password from default

### ISSUE THREAD

**Issue by rlheureu** [miguelgrinberg/microblog#67]
I am at this step:

```
curl -XPUT 'http://elastic:changeme@localhost:9200/_xpack/security/user/elastic/_password' -H "Content-Type: application/json" -d '{"password" : "<elastic-password>"}'
```

When I enter this in, I am seeing this error:

```
No handler found for uri [/_xpack/security/user/elastic/_password] and method [PUT](venv)
```
As I'm googling around about this, I've found it's a frequent error with a lot of possible causes but I can't determine which this might be, as I've successfully recreated everything else in the tutorial up to this point. Any idea?

**Comment by miguelgrinberg** [comment]
Which version of the elasticsearch docker container image are you using? Looks like there's been changes in the 6.x.x releases, I'm going to update the chapter with more accurate instructions in a little bit.

**Comment by rlheureu** [comment]
5.6.3 (what's specified in the tutorial).

**Comment by miguelgrinberg** [comment]
Not sure how these changes affect the 5.6.3 version, but in any case, going to the 6.1.1 release, authentication is now included only in the non-open source containers. The command to start the container is:

    docker run --name elasticsearch -d -p 9200:9200 -p 9300:9300 --rm -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1

This service will not require a password, so when you start the microblog container (which is fine because the container will not be listening in the external network anyway), so just set `ELASTICSEARCH_URI=http://elasticsearch:9200`.

Just tested these instructions and go it working. I will update Chapter 19 as above.

**Comment by miguelgrinberg** [comment]
The book is now updated to use the 6.1.1 open-source image. Note that as part of this update I changed `ELASTICSEARCH_URI` to `ELASTICSEARCH_URL`. This seemed like an inconsistence since I have `DATABASE_URL` and `REDIS_URL`.
