### ISSUE TITLE
Example on how delete a post

### ISSUE THREAD

**Issue by greyli** [miguelgrinberg/microblog#92]
Hi, Miguel!

I notice that there is a delete link in [the screenshot on the Kickstarter page](https://www.kickstarter.com/projects/1124925856/the-new-and-improved-flask-mega-tutorial), but I didn't find the implementation both in the book and the source code. Why does it missing?

**Comment by miguelgrinberg** [comment]
That screenshot was generated from the old version of microblog before the new version existed. You can review the old articles to see the delete functionality, that was something I decided to cut from the new version because it was related to an obscure bug in the flask extension for whoosh, which I'm not using anymore. If you want to see what this was about, the old tutorial is still on my blog: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvi-debugging-testing-and-profiling-legacy

**Comment by greyli** [comment]
Thanks very much!
