### ISSUE TITLE
Can't find flask_migrate for the import

### ISSUE THREAD

**Issue by tnovak123** [miguelgrinberg/microblog#97]
From flask_migrate import Migrate
Gives me E0401:Unable to import 'flask-migrate'. But pip installed and upgraded flask-migrate just fine.

**Comment by miguelgrinberg** [comment]
Where do you see the E0401 error? Are you using pylint or similar? I suggest you try to run the application and see if Python itself reports the error instead of relying on a linter.

**Comment by tnovak123** [comment]
Yes Pylint is what is giving me the error. I also get errors when i am
running the code at the command line. I am still a bit of a newbie with
Flask. As a result, i am not sure how to find the answer myself. I am
running vscode on windows 10. I am also using mysql through mamp for
windows. So executing the code i wrote to use mysql doesn't exactly match
up with the book. I just finished ch 4 also.

**Comment by miguelgrinberg** [comment]
Let me see the error from Python please. Linters can sometimes be misleading.

**Comment by tnovak123** [comment]
Here is my command line difficulties.
(flask-env)
Marla@MiniLump MINGW64 ~/lc101/microblog (master)
$ flask db init
Usage: flask db init [OPTIONS]

Error: Could not locate Flask application. You did not provide the
FLASK_APP environment variable.

For more information see http://flask.pocoo.org/docs/latest/quickstart/
(flask-env)
Marla@MiniLump MINGW64 ~/lc101/microblog (master)
$

**Comment by miguelgrinberg** [comment]
The error message is correct, you did not set your `FLASK_APP` environment variable. Please review chapter 1 of the tutorial regarding how to use the `flask` command.

**Comment by tnovak123** [comment]
I am having difficulty understanding why i have to keep resetting the
flask_app environment variable. when i run the code in the virtual
environment, I.e. python microblog.py, everything executes the way it
should. but when i do it the way you suggest in the book it keeps throwing
this error. plus my flask run command never works.

I am going through a coder bootcamp class by LaunchCode, and they taught us
a slightly different way that seems to make the code run just fine. I did
have to add some code to the program to make it run though. i have this new
code shielded by an if statement, "
if __name__ == '__main__':

**Comment by tnovak123** [comment]
Also, when i set the flask_app variable, the computer doesn't seem to keep
it because the same error shows up again.

**Comment by miguelgrinberg** [comment]
@tnovak123 Sorry this is so confusing. Let me start by saying that this is not you, some recent changes in Flask (which I did not agree with) have made starting an application very confusing, specially for beginners.

There are two ways to start a Flask server. The legacy way is what you were told in your class. The currently recommended way is what I show in my tutorial, which is based on the `flask` command. I'm not going to go into details because I don't want to confuse you even more, but there are some reasons why the new way is better. Unfortunately the new way is a bit annoying, in that you have to set `FLASK_APP` in your environment for the `flask` command to run.

> Also, when i set the flask_app variable, the computer doesn't seem to keep
it because the same error shows up again.

Yes, this is correct, environment variables are not remembered from one session to the next, they have to be set again, unless you figure out a way to automatically set them. If it annoys you to have to set the variable every time, you can look for a way to have it set when you log in, which is donei n different ways depending on what operating system that you have.

The next Flask release comes with its own method to "remember" the value of `FLASK_APP`, so this pain is going to be temporary.

**Comment by tnovak123** [comment]
awesome, i can put in my environment variables permanently, but this
program wont always be running from the command line. I am trying to get to
the point where i can do most things after the code begins to execute in
the flask environment. This is my main testing environment so it's not
live. I have been skipping most of the spots where you use the command line
and try to just write the code so I have a fully working program. I am
wondering if i just skip the flask_migrate coding for now and come back to
it once i have a better understanding of the issues on how to fix my
difficulties...is that going to break the final program? or a more simple
way to ask the question is...How integral to having the flask-migrate
portion of the program to the final programs normal function? I already
know how to work sql directly, and I know how to use flask to create and
remove tables with their structure. Can i just use that for the time being
until i become more familiar with how to solve the flask, or python issues
on windows?

**Comment by miguelgrinberg** [comment]
I'm sorry but there is something in your line of thinking that I do not understand.

> but this program wont always be running from the command line

There are three ways to run your Flask application. You can run it from an IDE such as PyCharm or Code during development, you can run it from the command-line also during development, and finally, for production, you typically use operating system facilities to start your application as a service with a production-grade web server, which is fairly similar to running from the command-line.

The IDE method to running Flask become very difficult once the `flask` command was introduced, but running from the command-line is not a problem, because in both it is fairly easy to set environment variables. Running as a service may or may not require the `FLASK_APP` environment variable to be set, usually you do need it so that you can make database changes, but not specifically to start the server.

So I believe if you are going to use one way to start your application during development that should be command-line, because that is the closest to how the application is going to run in production. If you can also make it work for the IDE that's great, but command-line is the most important in my opinion.

I can't really give you advice on what to skip or not skip from my tutorial. I think the more you skip the harder it will be for you to adapt my instructions to your particular situation. Database migrations may seem hard to you, but once you understand it it is actually a great way to manage your database without having to go down to the SQL level. If you prefer to use SQL then you can, but a large part of this tutorial is based on Flask-SQLAlchemy and Flask-Migrate, so you are constantly going to have to find alternative solutions to things, and those are going to be harder and more complex, you may not think so now, but these two extensions do make things a lot easier in terms of database management.

**Comment by tnovak123** [comment]
to answer the first question is that I start the program with the command
line. after i have started it there I switch to the web browser to
interface with the program to test it. I don't stay at the command line
interface to test it.

I want to keep the sqlalchemy part of the code just to interface with the
database, and basically have a working program for my project, I do intend
to credit you fully for the main program, and for the modifications i
credit myself too. I am presently just trying to relearn how to use flask
fully. My class didn't do such a great job at that part. They used videos
instead of a book setup. For me videos are too time consuming to go back to
so i can find a single piece of the training to remember that part. Also
they didn't quite employ the separation of concerns that you and I like to
go by. I prefer most of my code to be clean and easy to read and to have
separated for editing and debugging as well as modification.

I supposed that i could just bypass the migration part to have a running
blog program. and once i have more time to figure out why that part isn't
working then reintegrate it by using it. I was fully intending on writing
the code now, but figuring out why it isn't working later, for the
migration part that is. The rest of the code is working just fine. I
already know that my modification for using a mysql database in mamp is
working just fine. I just had to create the database structure with the
db.create_all() function for right now.

**Comment by miguelgrinberg** [comment]
> I just had to create the database structure with the
db.create_all() function for right now.

But soon enough I'll be making changes to the database schema. Those are going to be tricky to do by hand, that is why I prefer to teach Flask-Migrate from the start. As I said, it's really up to you to decide what to skip, but my opinion is that you are going to have a harder time, versus spending a few more minutes and getting to the bottom of the problem now.

**Comment by miguelgrinberg** [comment]
I don't understand what you mean, sorry. Why do you resist setting an environment variable so much? Once you set this variable the `flask` command will work. You are on Windows, correct? Just do this:

```
set FLASK_APP=microblog.py
```

Right after that, try this:

```
flask db init
```

If that does not work, show me the output in your terminal window.

**Comment by tnovak123** [comment]
this is why

(flask-env)
Marla@MiniLump MINGW64 ~/lc101/microblog (master)
$ set FLASK_APP=microblog
(flask-env)
Marla@MiniLump MINGW64 ~/lc101/microblog (master)
$ flask db init
Usage: flask db init [OPTIONS]

Error: Could not locate Flask application. You did not provide the
FLASK_APP environment variable.

For more information see http://flask.pocoo.org/docs/latest/quickstart/
(flask-env)
Marla@MiniLump MINGW64 ~/lc101/microblog (master)
$

**Comment by miguelgrinberg** [comment]
You are not using the windows command prompt here. Mingw64 is a unix emulation shell, you seem to be running bash or similar here. You need to use the Unix instructions:

```
export FLASK_APP=microblog.py
flask db init
```

**Comment by tnovak123** [comment]
i see, that works. Thank you very much for helping me understand that
bash=unix commands from your book. It did run just fine. So now i am
guessing that since it ran just fine the flask_migrate is working properly?

here is the output code from those commands

(flask-env)
Marla@MiniLump MINGW64 ~/lc101/microblog (master)
$ export FLASK_APP=microblog.py
(flask-env)
Marla@MiniLump MINGW64 ~/lc101/microblog (master)
$ flask db init
Creating directory C:\Users\Marla\lc101\microblog\migrations ... done
Creating directory C:\Users\Marla\lc101\microblog\migrations\versions ...
done
Generating C:\Users\Marla\lc101\microblog\migrations\alembic.ini ... done
Generating C:\Users\Marla\lc101\microblog\migrations\env.py ... done
Generating C:\Users\Marla\lc101\microblog\migrations\README ... done
Generating C:\Users\Marla\lc101\microblog\migrations\script.py.mako ... done
Please edit configuration/connection/logging settings in
'C:\\Users\\Marla\\lc101\\microblog\\migrations\\alembic.ini' before
proceeding.
(flask-env)
Marla@MiniLump MINGW64 ~/lc101/microblog (master)
$

**Comment by miguelgrinberg** [comment]
Yes, that is the expected output, which you can also see in my tutorial. Congrats!

**Comment by tnovak123** [comment]
Thank you very much...I think this one was my fault. I am a native windows
user, when working with Linux, which i dislike for various reasons which i
will not go into here, i often get confused as to which command prompt i am
actually using. I am using the git bash prompt most of the time with my
class. Anyway, I was just unsure if bash and sh which is what you referred
to in your book were close enough to think of as the same.

**Comment by miguelgrinberg** [comment]
Well, you are beginning, so you are allowed to be confused about things, I would not hold that against you. Sorry it took me a while to figure out how to help you, should have asked you to show me the terminal output right from the beginning.

**Comment by ChanForPres** [comment]
Hey! I ran the `export FLASK_APP=microblog.py` but `echo $FLASK_RUN` ouputs a blank line.. Any ideas? @miguelgrinberg

**Comment by ChanForPres** [comment]
Somehow fixed it.. Solution is here:

http://osxdaily.com/2015/07/28/set-enviornment-variables-mac-os-x/
https://stackoverflow.com/questions/37826016/env-variables-not-set-while-running-minimal-flask-application

**Comment by PCSailor** [comment]
I had these 2 errors:
`Unable to import 'flask_sqlalchemy' Unable to import 'flask_migrate'`
The problem was this line in my models.py file:
`id = db.Column(db.Integer, primary_key=True)`
I had a comma at end of the line and it caused me an hour of wasted time.
